# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20160510_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='files',
        ),
        migrations.AddField(
            model_name='submission',
            name='review_files',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.review_directory_path),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_files',
            field=models.FileField(default=datetime.datetime(2016, 5, 12, 16, 21, 49, 831626, tzinfo=utc), upload_to=projects.models.submission_directory_path),
            preserve_default=False,
        ),
    ]
