# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20160512_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='finished_time',
        ),
    ]
