# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
    ]
