# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
