# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20160602_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='starter',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.starter_directory_path),
        ),
    ]
