# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160508_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='The description goes here. This is descriptive text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(default='The description goes here. This is descriptive text'),
            preserve_default=False,
        ),
    ]
