# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160508_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='review',
            name='project',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='cost',
        ),
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='assined_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='files',
            field=models.FileField(default=0, upload_to=projects.models.review_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='finished_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='returned_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
