# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 23:17
from __future__ import unicode_literals

import demo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_a', models.TextField()),
                ('q_b', models.TextField()),
                ('review_files', models.FileField(blank=True, null=True, upload_to=demo.models.review_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
