# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20160606_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intro',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
