# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20160606_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='reviewing',
            field=models.BooleanField(default=True),
        ),
    ]
